### ISSUE TITLE
A lot of deprecated messages from @bem/entity-name

### ISSUE THREAD

**Issue by shkarupa-alex** [bem-sdk-archive/bem-decl#117]
Clone, 
run npm i, 
run npm test
see a lot of messages like:

@bem/entity-name deprecated `modName` is kept just for compatibility and can be dropped in the future. Use `mod.name` instead in `{ block: 'block', modName: 'mod', modVal: true }` at at node_modules/@bem/entity-name/lib/entity-name.js:32:24

@bem/entity-name deprecated `modVal` is kept just for compatibility and can be dropped in the future. Use `mod.val` instead in `{ block: 'block', modName: 'mod', modVal: true }` at at node_modules/@bem/entity-name/lib/entity-name.js:33:23

**Comment by qfox** [comment]
Yeah, need to update that package. Don't have much time for that unfortunately ;-(
